import 'package:belotable/domain/concours/concours.dart';
import 'package:belotable/domain/concours/concours_statut.dart';
import 'package:belotable/domain/doublettes/doublette.dart';
import 'package:belotable/domain/manches/table_de_jeu.dart';
import 'package:belotable/domain/manches/table_doublette.dart';
import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';

/// Database schema and DAOs.
///
/// Generated by drift_dev when running `build_runner build`.
part 'app_database.g.dart';

/// Table schema for storing competition events.
class ConcoursTable extends Table {
  /// Unique identifier.
  TextColumn get id => text()();

  /// Competition date.
  DateTimeColumn get date => dateTime()();

  /// Venue location.
  TextColumn get lieu => text()();

  /// Organizing entity.
  TextColumn get organisateur => text()();

  /// Number of deals per round.
  IntColumn get nombreDonnesParManche =>
      integer().withDefault(const Constant(10))();

  /// Maximum points per deal.
  IntColumn get nombreMaxPointsParDonne =>
      integer().withDefault(const Constant(162))();

  /// Game rules text.
  TextColumn get reglesJeu => text()();

  /// Contest status: Initialisation, EnCours, Termine.
  TextColumn get statutConcours =>
      text().withDefault(const Constant('initialisation'))();

  @override
  Set<Column<Object>> get primaryKey => {id};
}

/// Table schema for storing registered doublettes per concours.
class DoublettesTable extends Table {
  /// Owning concours id.
  TextColumn get concoursId =>
      text().references(ConcoursTable, #id, onDelete: KeyAction.cascade)();

  /// Registration order id scoped to concours.
  IntColumn get doubletteId => integer()();

  /// Player A full name.
  TextColumn get joueurA => text()();

  /// Player B full name.
  TextColumn get joueurB => text()();

  /// Team name unique per concours.
  TextColumn get nomEquipe => text()();

  /// Aggregated points across all manches.
  IntColumn get totalPoints => integer().withDefault(const Constant(0))();

  @override
  Set<Column<Object>> get primaryKey => {concoursId, doubletteId};

  @override
  List<Set<Column<Object>>> get uniqueKeys => [
    {concoursId, nomEquipe},
  ];
}

/// Table schema for storing rounds (manches) within a concours.
class ManchesTable extends Table {
  /// Auto-incremented primary key.
  IntColumn get id => integer().autoIncrement()();

  /// Owning concours id.
  TextColumn get concoursId =>
      text().references(ConcoursTable, #id, onDelete: KeyAction.cascade)();

  /// Round number, starting at 1.
  IntColumn get numero => integer()();
}

/// Table schema for storing match tables within a round.
class TablesDeJeuTable extends Table {
  /// Auto-incremented primary key.
  IntColumn get id => integer().autoIncrement()();

  /// Owning manche id.
  IntColumn get mancheId =>
      integer().references(ManchesTable, #id, onDelete: KeyAction.cascade)();

  /// Table number within round, starting at 1.
  IntColumn get numero => integer()();

  /// Computed status stored as string.
  TextColumn get statut => text().withDefault(const Constant('En attente'))();
}

/// Table schema for doublette participation in a match table.
class TableDoublettesTable extends Table {
  /// Owning table id.
  IntColumn get tableId => integer().references(
    TablesDeJeuTable,
    #id,
    onDelete: KeyAction.cascade,
  )();

  /// Owning concours id (matches doublette scope).
  TextColumn get concoursId => text()();

  /// Doublette registration id.
  IntColumn get doubletteId => integer()();

  /// Points achieved in this table.
  IntColumn get points => integer().withDefault(const Constant(0))();

  /// Team status in this table stored as string.
  TextColumn get statut => text().withDefault(const Constant('En attente'))();

  @override
  Set<Column<Object>> get primaryKey => {tableId, concoursId, doubletteId};
}

/// Data Access Object for Concours table operations.
@DriftAccessor(tables: [ConcoursTable, DoublettesTable])
class ConcoursDao extends DatabaseAccessor<AppDatabase>
    with _$ConcoursDaoMixin {
  /// Creates DAO bound to the given database.
  ConcoursDao(super.attachedDatabase);

  /// Inserts or updates concours in database.
  Future<void> insertConcours(Concours concours) async {
    await into(concoursTable).insertOnConflictUpdate(
      ConcoursTableCompanion(
        id: Value(concours.id),
        date: Value(concours.date),
        lieu: Value(concours.lieu),
        organisateur: Value(concours.organisateur),
        nombreDonnesParManche: Value(concours.nombreDonnesParManche),
        nombreMaxPointsParDonne: Value(concours.nombreMaxPointsParDonne),
        reglesJeu: Value(concours.reglesJeu),
        statutConcours: Value(concours.statutConcours.name),
      ),
    );
  }

  /// Returns concours by id or null when absent.
  Future<Concours?> findConcoursById(String id) async {
    final row = await (select(
      concoursTable,
    )..where((tbl) => tbl.id.equals(id))).getSingleOrNull();

    if (row == null) {
      return null;
    }

    return Concours(
      id: row.id,
      date: row.date,
      lieu: row.lieu,
      organisateur: row.organisateur,
      nombreDonnesParManche: row.nombreDonnesParManche,
      nombreMaxPointsParDonne: row.nombreMaxPointsParDonne,
      reglesJeu: row.reglesJeu,
      statutConcours: ConcoursStatut.fromString(row.statutConcours),
    );
  }

  /// Returns all concours sorted from most recent to oldest date.
  Future<List<Concours>> findAllConcoursByDateDesc() async {
    final joinedRows =
        await (select(concoursTable)..orderBy([
              (table) => OrderingTerm.desc(table.date),
            ]))
            .join([
              leftOuterJoin(
                doublettesTable,
                doublettesTable.concoursId.equalsExp(concoursTable.id),
              ),
            ])
            .get();

    final groupedCounts = <String, int>{};
    final concoursById = <String, ConcoursTableData>{};

    for (final row in joinedRows) {
      final concoursRow = row.readTable(concoursTable);
      concoursById[concoursRow.id] = concoursRow;

      final doubletteRow = row.readTableOrNull(doublettesTable);
      if (doubletteRow != null) {
        groupedCounts[concoursRow.id] =
            (groupedCounts[concoursRow.id] ?? 0) + 1;
      }
    }

    return concoursById.values
        .map(
          (row) => Concours(
            id: row.id,
            date: row.date,
            lieu: row.lieu,
            organisateur: row.organisateur,
            nombreDoublettes: groupedCounts[row.id] ?? 0,
            nombreDonnesParManche: row.nombreDonnesParManche,
            nombreMaxPointsParDonne: row.nombreMaxPointsParDonne,
            reglesJeu: row.reglesJeu,
            statutConcours: ConcoursStatut.fromString(row.statutConcours),
          ),
        )
        .toList(growable: false);
  }

  /// Returns the count of all concours entries in the database.
  Future<int> countConcours() async {
    final countExpression = concoursTable.id.count();
    final query = selectOnly(concoursTable)..addColumns([countExpression]);
    final row = await query.getSingle();

    return row.read(countExpression) ?? 0;
  }

  /// Deletes a concours by id and cascades delete to related data.
  /// Returns true if deletion was successful, false if concours not found.
  Future<bool> deleteConcoursById(String id) async {
    final result = await (delete(
      concoursTable,
    )..where((tbl) => tbl.id.equals(id))).go();
    return result > 0;
  }
}

/// Data Access Object for Doublettes table operations.
@DriftAccessor(tables: [DoublettesTable])
class DoublettesDao extends DatabaseAccessor<AppDatabase>
    with _$DoublettesDaoMixin {
  /// Creates DAO bound to the given database.
  DoublettesDao(super.attachedDatabase);

  /// Inserts a new doublette with next id in concours.
  Future<Doublette> createDoublette({
    required String concoursId,
    required String joueurA,
    required String joueurB,
    required String nomEquipe,
  }) async {
    return transaction(() async {
      final maxIdExpr = doublettesTable.doubletteId.max();
      final maxIdRow =
          await (selectOnly(doublettesTable)
                ..addColumns([maxIdExpr])
                ..where(doublettesTable.concoursId.equals(concoursId)))
              .getSingle();
      final nextId = (maxIdRow.read(maxIdExpr) ?? 0) + 1;

      await into(doublettesTable).insert(
        DoublettesTableCompanion.insert(
          concoursId: concoursId,
          doubletteId: nextId,
          joueurA: joueurA,
          joueurB: joueurB,
          nomEquipe: nomEquipe,
        ),
      );

      return Doublette(
        concoursId: concoursId,
        doubletteId: nextId,
        joueurA: joueurA,
        joueurB: joueurB,
        nomEquipe: nomEquipe,
      );
    });
  }

  /// Updates one doublette by composite key.
  Future<Doublette> updateDoublette(Doublette doublette) async {
    await (update(doublettesTable)..where(
          (tbl) =>
              tbl.concoursId.equals(doublette.concoursId) &
              tbl.doubletteId.equals(doublette.doubletteId),
        ))
        .write(
          DoublettesTableCompanion(
            joueurA: Value(doublette.joueurA),
            joueurB: Value(doublette.joueurB),
            nomEquipe: Value(doublette.nomEquipe),
            totalPoints: Value(doublette.totalPoints),
          ),
        );

    return doublette;
  }

  /// Returns one doublette by composite key.
  Future<Doublette?> findDoubletteById({
    required String concoursId,
    required int doubletteId,
  }) async {
    final row =
        await (select(doublettesTable)..where(
              (tbl) =>
                  tbl.concoursId.equals(concoursId) &
                  tbl.doubletteId.equals(doubletteId),
            ))
            .getSingleOrNull();

    if (row == null) {
      return null;
    }

    return Doublette(
      concoursId: row.concoursId,
      doubletteId: row.doubletteId,
      joueurA: row.joueurA,
      joueurB: row.joueurB,
      nomEquipe: row.nomEquipe,
      totalPoints: row.totalPoints,
    );
  }

  /// Lists all doublettes for one concours ordered by id.
  Future<List<Doublette>> findDoublettesByConcoursId(String concoursId) async {
    final rows =
        await (select(doublettesTable)
              ..where((tbl) => tbl.concoursId.equals(concoursId))
              ..orderBy([(tbl) => OrderingTerm.asc(tbl.doubletteId)]))
            .get();

    return rows
        .map(
          (row) => Doublette(
            concoursId: row.concoursId,
            doubletteId: row.doubletteId,
            joueurA: row.joueurA,
            joueurB: row.joueurB,
            nomEquipe: row.nomEquipe,
            totalPoints: row.totalPoints,
          ),
        )
        .toList(growable: false);
  }

  /// Returns true when team name already exists in concours.
  Future<bool> teamNameExists({
    required String concoursId,
    required String nomEquipe,
    int? excludingDoubletteId,
  }) async {
    final normalizedTeamName = nomEquipe.toLowerCase();
    final query = selectOnly(doublettesTable)
      ..addColumns([doublettesTable.doubletteId.count()])
      ..where(doublettesTable.concoursId.equals(concoursId))
      ..where(doublettesTable.nomEquipe.lower().equals(normalizedTeamName));

    if (excludingDoubletteId != null) {
      query.where(doublettesTable.doubletteId.isNotValue(excludingDoubletteId));
    }

    final row = await query.getSingle();
    return (row.read(doublettesTable.doubletteId.count()) ?? 0) > 0;
  }

  /// Deletes one doublette by composite key.
  Future<bool> deleteDoublette({
    required String concoursId,
    required int doubletteId,
  }) async {
    final result =
        await (delete(doublettesTable)..where(
              (tbl) =>
                  tbl.concoursId.equals(concoursId) &
                  tbl.doubletteId.equals(doubletteId),
            ))
            .go();

    return result > 0;
  }
}

/// Data Access Object for Manches, TablesDeJeu and TableDoublettes operations.
@DriftAccessor(
  tables: [
    ManchesTable,
    TablesDeJeuTable,
    TableDoublettesTable,
    DoublettesTable,
  ],
)
class ManchesDao extends DatabaseAccessor<AppDatabase> with _$ManchesDaoMixin {
  /// Creates DAO bound to the given database.
  ManchesDao(super.attachedDatabase);

  /// Inserts a manche and returns the inserted row with generated id.
  Future<ManchesTableData> insertManche(ManchesTableCompanion companion) async {
    final id = await into(manchesTable).insert(companion);
    return (select(manchesTable)..where((t) => t.id.equals(id))).getSingle();
  }

  /// Inserts a table de jeu and returns the inserted row.
  Future<TablesDeJeuTableData> insertTableDeJeu(
    TablesDeJeuTableCompanion companion,
  ) async {
    final id = await into(tablesDeJeuTable).insert(companion);
    return (select(
      tablesDeJeuTable,
    )..where((t) => t.id.equals(id))).getSingle();
  }

  /// Inserts a table-doublette participation row.
  Future<void> insertTableDoublette(
    TableDoublettesTableCompanion companion,
  ) async {
    await into(tableDoublettesTable).insert(companion);
  }

  /// Returns all manches for a concours ordered by numero.
  Future<List<ManchesTableData>> findManchesByConcoursId(
    String concoursId,
  ) async {
    return (select(manchesTable)
          ..where((t) => t.concoursId.equals(concoursId))
          ..orderBy([(t) => OrderingTerm.asc(t.numero)]))
        .get();
  }

  /// Returns true if any manche exists for the given concours.
  Future<bool> mancheExistsPourConcours(String concoursId) async {
    final countExpr = manchesTable.id.count();
    final query = selectOnly(manchesTable)
      ..addColumns([countExpr])
      ..where(manchesTable.concoursId.equals(concoursId));
    final row = await query.getSingle();
    return (row.read(countExpr) ?? 0) > 0;
  }

  /// Returns tables with their doublettes for a manche, ordered by numero.
  Future<List<TableDeJeu>> findTablesDeJeuByMancheId(int mancheId) async {
    final tableRows =
        await (select(tablesDeJeuTable)
              ..where((t) => t.mancheId.equals(mancheId))
              ..orderBy([(t) => OrderingTerm.asc(t.numero)]))
            .get();

    final result = <TableDeJeu>[];
    for (final tableRow in tableRows) {
      final participations = await _loadDoublettesForTable(tableRow.id);
      result.add(
        TableDeJeu(
          id: tableRow.id,
          mancheId: tableRow.mancheId,
          numero: tableRow.numero,
          statut: TableDeJeuStatut.fromDb(tableRow.statut),
          doublettes: participations,
        ),
      );
    }
    return result;
  }

  Future<List<TableDoublette>> _loadDoublettesForTable(int tableId) async {
    final rows = await (select(tableDoublettesTable).join([
      innerJoin(
        doublettesTable,
        doublettesTable.concoursId.equalsExp(tableDoublettesTable.concoursId) &
            doublettesTable.doubletteId.equalsExp(
              tableDoublettesTable.doubletteId,
            ),
      ),
    ])..where(tableDoublettesTable.tableId.equals(tableId))).get();

    return rows
        .map((row) {
          final td = row.readTable(tableDoublettesTable);
          final d = row.readTable(doublettesTable);
          return TableDoublette(
            tableId: td.tableId,
            concoursId: td.concoursId,
            doubletteId: td.doubletteId,
            points: td.points,
            statut: TableDoubletteStatut.fromDb(td.statut),
            nomEquipe: d.nomEquipe,
          );
        })
        .toList(growable: false);
  }

  /// Returns id of the first table in the latest manche with < 2 doublettes.
  Future<int?> findFirstAvailableTableId(String concoursId) async {
    final latestManche =
        await (select(manchesTable)
              ..where((t) => t.concoursId.equals(concoursId))
              ..orderBy([(t) => OrderingTerm.desc(t.numero)])
              ..limit(1))
            .getSingleOrNull();
    if (latestManche == null) {
      return null;
    }

    final tableRows =
        await (select(tablesDeJeuTable)
              ..where((t) => t.mancheId.equals(latestManche.id))
              ..orderBy([(t) => OrderingTerm.asc(t.numero)]))
            .get();

    for (final table in tableRows) {
      final countExpr = tableDoublettesTable.doubletteId.count();
      final query = selectOnly(tableDoublettesTable)
        ..addColumns([countExpr])
        ..where(tableDoublettesTable.tableId.equals(table.id));
      final row = await query.getSingle();
      final count = row.read(countExpr) ?? 0;
      if (count < 2) {
        return table.id;
      }
    }

    return null;
  }

  /// Adds a doublette to a specific table.
  Future<void> addDoubletteToTable({
    required int tableId,
    required String concoursId,
    required int doubletteId,
  }) async {
    final targetTable = await (select(
      tablesDeJeuTable,
    )..where((t) => t.id.equals(tableId))).getSingleOrNull();
    if (targetTable == null) {
      return;
    }

    final countExpr = tableDoublettesTable.doubletteId.count();
    final countQuery = selectOnly(tableDoublettesTable)
      ..addColumns([countExpr])
      ..where(tableDoublettesTable.tableId.equals(tableId));
    final countRow = await countQuery.getSingle();
    final count = countRow.read(countExpr) ?? 0;
    if (count >= 2) {
      return;
    }

    final existingInSameManche =
        await (select(tableDoublettesTable).join([
              innerJoin(
                tablesDeJeuTable,
                tablesDeJeuTable.id.equalsExp(tableDoublettesTable.tableId),
              ),
            ])..where(
              tableDoublettesTable.concoursId.equals(concoursId) &
                  tableDoublettesTable.doubletteId.equals(doubletteId) &
                  tablesDeJeuTable.mancheId.equals(targetTable.mancheId),
            ))
            .getSingleOrNull();

    if (existingInSameManche != null) {
      return;
    }

    await into(tableDoublettesTable).insert(
      TableDoublettesTableCompanion.insert(
        tableId: tableId,
        concoursId: concoursId,
        doubletteId: doubletteId,
      ),
    );
  }

  /// Assigns doublette to latest manche table or creates a new table if needed.
  Future<void> assignDoubletteToLatestManche({
    required String concoursId,
    required int doubletteId,
  }) async {
    await transaction(() async {
      final latestManche =
          await (select(manchesTable)
                ..where((t) => t.concoursId.equals(concoursId))
                ..orderBy([(t) => OrderingTerm.desc(t.numero)])
                ..limit(1))
              .getSingleOrNull();

      if (latestManche == null) {
        return;
      }

      final alreadyAssigned =
          await (select(tableDoublettesTable).join([
                innerJoin(
                  tablesDeJeuTable,
                  tablesDeJeuTable.id.equalsExp(tableDoublettesTable.tableId),
                ),
              ])..where(
                tableDoublettesTable.concoursId.equals(concoursId) &
                    tableDoublettesTable.doubletteId.equals(doubletteId) &
                    tablesDeJeuTable.mancheId.equals(latestManche.id),
              ))
              .getSingleOrNull();

      if (alreadyAssigned != null) {
        return;
      }

      var targetTableId = await findFirstAvailableTableId(concoursId);
      if (targetTableId == null) {
        final maxNumeroExpr = tablesDeJeuTable.numero.max();
        final maxNumeroQuery = selectOnly(tablesDeJeuTable)
          ..addColumns([maxNumeroExpr])
          ..where(tablesDeJeuTable.mancheId.equals(latestManche.id));
        final maxNumeroRow = await maxNumeroQuery.getSingle();
        final nextNumero = (maxNumeroRow.read(maxNumeroExpr) ?? 0) + 1;

        final newTable = await insertTableDeJeu(
          TablesDeJeuTableCompanion.insert(
            mancheId: latestManche.id,
            numero: nextNumero,
          ),
        );
        targetTableId = newTable.id;
      }

      await addDoubletteToTable(
        tableId: targetTableId,
        concoursId: concoursId,
        doubletteId: doubletteId,
      );
    });
  }

  /// Returns the table-doublette record for a doublette, or null.
  Future<TableDoublette?> findTableDoublette({
    required String concoursId,
    required int doubletteId,
  }) async {
    final rows =
        await (select(tableDoublettesTable).join([
              innerJoin(
                doublettesTable,
                doublettesTable.concoursId.equalsExp(
                      tableDoublettesTable.concoursId,
                    ) &
                    doublettesTable.doubletteId.equalsExp(
                      tableDoublettesTable.doubletteId,
                    ),
              ),
            ])..where(
              tableDoublettesTable.concoursId.equals(concoursId) &
                  tableDoublettesTable.doubletteId.equals(doubletteId),
            ))
            .get();

    if (rows.isEmpty) {
      return null;
    }

    final row = rows.first;
    final td = row.readTable(tableDoublettesTable);
    final d = row.readTable(doublettesTable);
    return TableDoublette(
      tableId: td.tableId,
      concoursId: td.concoursId,
      doubletteId: td.doubletteId,
      points: td.points,
      statut: TableDoubletteStatut.fromDb(td.statut),
      nomEquipe: d.nomEquipe,
    );
  }

  /// Returns all table-doublette records for a doublette across all manches,
  /// ordered by manche numero ascending.
  Future<List<TableDoublette>> findTableDoublettesByDoubletteId({
    required String concoursId,
    required int doubletteId,
  }) async {
    final rows =
        await (select(tableDoublettesTable).join([
                innerJoin(
                  doublettesTable,
                  doublettesTable.concoursId.equalsExp(
                        tableDoublettesTable.concoursId,
                      ) &
                      doublettesTable.doubletteId.equalsExp(
                        tableDoublettesTable.doubletteId,
                      ),
                ),
                innerJoin(
                  tablesDeJeuTable,
                  tablesDeJeuTable.id.equalsExp(tableDoublettesTable.tableId),
                ),
                innerJoin(
                  manchesTable,
                  manchesTable.id.equalsExp(tablesDeJeuTable.mancheId),
                ),
              ])
              ..where(
                tableDoublettesTable.concoursId.equals(concoursId) &
                    tableDoublettesTable.doubletteId.equals(doubletteId),
              )
              ..orderBy([
                OrderingTerm.asc(manchesTable.numero),
              ]))
            .get();

    return rows
        .map((row) {
          final td = row.readTable(tableDoublettesTable);
          final d = row.readTable(doublettesTable);
          return TableDoublette(
            tableId: td.tableId,
            concoursId: td.concoursId,
            doubletteId: td.doubletteId,
            points: td.points,
            statut: TableDoubletteStatut.fromDb(td.statut),
            nomEquipe: d.nomEquipe,
          );
        })
        .toList(growable: false);
  }

  /// Removes a doublette from its table. Deletes the table if empty.
  Future<void> removeDoubletteFromTable({
    required String concoursId,
    required int doubletteId,
  }) async {
    final td = await findTableDoublette(
      concoursId: concoursId,
      doubletteId: doubletteId,
    );
    if (td == null) {
      return;
    }

    await (delete(tableDoublettesTable)..where(
          (t) =>
              t.tableId.equals(td.tableId) &
              t.concoursId.equals(concoursId) &
              t.doubletteId.equals(doubletteId),
        ))
        .go();

    // Delete table if now empty
    final remaining = await (select(
      tableDoublettesTable,
    )..where((t) => t.tableId.equals(td.tableId))).get();
    if (remaining.isEmpty) {
      await (delete(
        tablesDeJeuTable,
      )..where((t) => t.id.equals(td.tableId))).go();
    }
  }

  /// Updates points of a doublette in a table.
  Future<void> updatePoints({
    required int tableId,
    required String concoursId,
    required int doubletteId,
    required int points,
  }) async {
    await (update(tableDoublettesTable)..where(
          (t) =>
              t.tableId.equals(tableId) &
              t.concoursId.equals(concoursId) &
              t.doubletteId.equals(doubletteId),
        ))
        .write(TableDoublettesTableCompanion(points: Value(points)));
  }

  /// Updates statut of a doublette and applies opponent/table status rules.
  Future<TableDeJeu> updateStatutWithRules({
    required int tableId,
    required String concoursId,
    required int doubletteId,
    required TableDoubletteStatut statut,
  }) async {
    await (update(tableDoublettesTable)..where(
          (t) =>
              t.tableId.equals(tableId) &
              t.concoursId.equals(concoursId) &
              t.doubletteId.equals(doubletteId),
        ))
        .write(TableDoublettesTableCompanion(statut: Value(statut.label)));

    // Apply opponent rule
    if (statut != TableDoubletteStatut.gagne) {
      var opponentStatut = statut;
      if (statut == TableDoubletteStatut.perdu ||
          statut == TableDoubletteStatut.abandon) {
        opponentStatut = TableDoubletteStatut.gagne;
      }

      await (update(tableDoublettesTable)..where(
            (t) =>
                t.tableId.equals(tableId) &
                t.concoursId.equals(concoursId) &
                t.doubletteId.isNotValue(doubletteId),
          ))
          .write(
            TableDoublettesTableCompanion(statut: Value(opponentStatut.label)),
          );
    }

    // Recompute and persist table statut
    final participations = await _loadDoublettesForTable(tableId);
    final tableStatut = TableDeJeuStatut.fromDoublettes(participations);

    await (update(tablesDeJeuTable)..where((t) => t.id.equals(tableId))).write(
      TablesDeJeuTableCompanion(statut: Value(tableStatut.label)),
    );

    final tableRow = await (select(
      tablesDeJeuTable,
    )..where((t) => t.id.equals(tableId))).getSingle();

    return TableDeJeu(
      id: tableRow.id,
      mancheId: tableRow.mancheId,
      numero: tableRow.numero,
      statut: TableDeJeuStatut.fromDb(tableRow.statut),
      doublettes: participations,
    );
  }

  /// Returns all tables for a concours across all manches,
  /// ordered by manche numero then table numero.
  Future<List<TableDeJeu>> findTablesDeJeuByConcoursId(
    String concoursId,
  ) async {
    final tableRows =
        await (select(tablesDeJeuTable).join([
                innerJoin(
                  manchesTable,
                  manchesTable.id.equalsExp(tablesDeJeuTable.mancheId),
                ),
              ])
              ..where(manchesTable.concoursId.equals(concoursId))
              ..orderBy([
                OrderingTerm.asc(manchesTable.numero),
                OrderingTerm.asc(tablesDeJeuTable.numero),
              ]))
            .get();

    final result = <TableDeJeu>[];
    for (final row in tableRows) {
      final tableRow = row.readTable(tablesDeJeuTable);
      final participations = await _loadDoublettesForTable(tableRow.id);
      result.add(
        TableDeJeu(
          id: tableRow.id,
          mancheId: tableRow.mancheId,
          numero: tableRow.numero,
          statut: TableDeJeuStatut.fromDb(tableRow.statut),
          doublettes: participations,
        ),
      );
    }
    return result;
  }

  /// Merges two tables: moves all doublettes from
  /// source to target, deletes source.
  /// Both tables must exist.
  Future<void> mergeTableDoublettes({
    required int targetTableId,
    required int sourceTableId,
    required String concoursId,
  }) async {
    await transaction(() async {
      // Move all doublettes from source to target
      final sourceDoublettes = await (select(
        tableDoublettesTable,
      )..where((t) => t.tableId.equals(sourceTableId))).get();

      for (final sourceTd in sourceDoublettes) {
        // Update the doublette to point to target table
        await (update(tableDoublettesTable)..where(
              (t) =>
                  t.tableId.equals(sourceTableId) &
                  t.concoursId.equals(sourceTd.concoursId) &
                  t.doubletteId.equals(sourceTd.doubletteId),
            ))
            .write(
              TableDoublettesTableCompanion(tableId: Value(targetTableId)),
            );
      }

      // Delete source table
      await (delete(
        tablesDeJeuTable,
      )..where((t) => t.id.equals(sourceTableId))).go();

      // Recompute target table status
      final participations = await _loadDoublettesForTable(targetTableId);
      final tableStatut = TableDeJeuStatut.fromDoublettes(participations);

      await (update(
        tablesDeJeuTable,
      )..where((t) => t.id.equals(targetTableId))).write(
        TablesDeJeuTableCompanion(statut: Value(tableStatut.label)),
      );
    });
  }
}

/// Drift database instance for managing all application data.
@DriftDatabase(
  tables: [
    ConcoursTable,
    DoublettesTable,
    ManchesTable,
    TablesDeJeuTable,
    TableDoublettesTable,
  ],
  daos: [ConcoursDao, DoublettesDao, ManchesDao],
)
class AppDatabase extends _$AppDatabase {
  /// Creates database with optional custom executor for testing.
  AppDatabase([QueryExecutor? e])
    : super(
        e ??
            driftDatabase(
              name: 'belotable_db',
              native: const DriftNativeOptions(
                databaseDirectory: getApplicationSupportDirectory,
              ),
              web: DriftWebOptions(
                sqlite3Wasm: Uri.parse('sqlite3.wasm'),
                driftWorker: Uri.parse('drift_worker.js'),
                onResult: (result) {
                  if (result.missingFeatures.isNotEmpty) {
                    debugPrint(
                      'Using ${result.chosenImplementation} due to unsupported '
                      'browser features: ${result.missingFeatures}',
                    );
                  }
                },
              ),
            ),
      );

  /// Creates database with in-memory or custom executor for testing.
  AppDatabase.withExecutor(super.e);

  @override
  int get schemaVersion => 3;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) => m.createAll(),
    onUpgrade: (m, from, to) async {
      if (from < 2) {
        await m.createTable(doublettesTable);
      }
      if (from < 3) {
        await m.createTable(manchesTable);
        await m.createTable(tablesDeJeuTable);
        await m.createTable(tableDoublettesTable);
      }
    },
    beforeOpen: (details) async {
      await customStatement('PRAGMA foreign_keys = ON');
    },
  );
}
