import 'package:belotable/domain/concours/concours.dart';
import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';

/// Database schema and DAOs.
///
/// Generated by drift_dev when running `build_runner build`.
part 'app_database.g.dart';

/// Table schema for storing competition events.
class ConcoursTable extends Table {
  /// Unique identifier.
  TextColumn get id => text()();

  /// Competition date.
  DateTimeColumn get date => dateTime()();

  /// Venue location.
  TextColumn get lieu => text()();

  /// Organizing entity.
  TextColumn get organisateur => text()();

  @override
  Set<Column<Object>> get primaryKey => {id};
}

/// Data Access Object for Concours table operations.
@DriftAccessor(tables: [ConcoursTable])
class ConcoursDao extends DatabaseAccessor<AppDatabase>
    with _$ConcoursDaoMixin {
  /// Creates DAO bound to the given database.
  ConcoursDao(super.attachedDatabase);

  /// Inserts or updates concours in database.
  Future<void> insertConcours(Concours concours) async {
    await into(concoursTable).insertOnConflictUpdate(
      ConcoursTableCompanion.insert(
        id: concours.id,
        date: concours.date,
        lieu: concours.lieu,
        organisateur: concours.organisateur,
      ),
    );
  }

  /// Returns all concours sorted from most recent to oldest date.
  Future<List<Concours>> findAllConcoursByDateDesc() async {
    final query = select(concoursTable)
      ..orderBy([
        (table) => OrderingTerm.desc(table.date),
      ]);

    final rows = await query.get();

    return rows
        .map(
          (row) => Concours(
            id: row.id,
            date: row.date,
            lieu: row.lieu,
            organisateur: row.organisateur,
          ),
        )
        .toList(growable: false);
  }

  /// Returns the count of all concours entries in the database.
  Future<int> countConcours() async {
    final countExpression = concoursTable.id.count();
    final query = selectOnly(concoursTable)..addColumns([countExpression]);
    final row = await query.getSingle();

    return row.read(countExpression) ?? 0;
  }
}

/// Drift database instance for managing all application data.
@DriftDatabase(tables: [ConcoursTable], daos: [ConcoursDao])
class AppDatabase extends _$AppDatabase {
  /// Creates database with optional custom executor for testing.
  AppDatabase([QueryExecutor? e])
    : super(
        e ??
            driftDatabase(
              name: 'belotable_db',
              native: const DriftNativeOptions(
                databaseDirectory: getApplicationSupportDirectory,
              ),
              web: DriftWebOptions(
                sqlite3Wasm: Uri.parse('sqlite3.wasm'),
                driftWorker: Uri.parse('drift_worker.js'),
                onResult: (result) {
                  if (result.missingFeatures.isNotEmpty) {
                    debugPrint(
                      'Using ${result.chosenImplementation} due to unsupported '
                      'browser features: ${result.missingFeatures}',
                    );
                  }
                },
              ),
            ),
      );

  /// Creates database with in-memory or custom executor for testing.
  AppDatabase.withExecutor(super.e);

  @override
  int get schemaVersion => 1;
}
